`timescale 1ns / 1ps

// =============================================================================
// Module: clock_gen.v (OPTIMIZED FOR FPGA with PLL 4-outputs)
// Chức năng: Clock distribution using PLL with 4 synchronized outputs
//
// Architecture:
// 1. PLL Input: 100MHz from board oscillator
// 2. PLL Outputs (all synchronized to PLL):
//    - clk_out1 (400MHz) → K/DCO clocks for ADPLLs
//    - clk_out2 (25MHz) → fref_25mhz for Conventional ADPLL
//    - clk_out3 (12.5MHz) → fref_12_5mhz (alternative)
//    - clk_out4 (6.25MHz) → fref_6_25mhz (alternative)
// 3. Counter Enable: For 10 RO reference frequencies (100K-1000K)
// =============================================================================

module clock_gen (
    input  wire clk_100mhz,
    input  wire reset,
    
    // =========================================================================
    // T-FF Chain Outputs (Synchronous, Real Clock Signals)
    // =========================================================================
    output wire fref_50mhz,
    output wire fref_25mhz,
    output wire fref_12_5mhz,
    output wire fref_6_25mhz,
    
    // =========================================================================
    // PLL Output: 400MHz for K/DCO clocks (Conventional ADPLL)
    // =========================================================================
    output wire k_dco_400mhz,
    output wire k_dco_400mhz_locked,
    
    // =========================================================================
    // Counter Enable Outputs (10 RO Reference Frequencies)
    // Clock enable signals paired with DFF outputs in top module
    // =========================================================================
    output wire ce_fref_100khz,
    output wire ce_fref_200khz,
    output wire ce_fref_300khz,
    output wire ce_fref_400khz,
    output wire ce_fref_500khz,
    output wire ce_fref_600khz,
    output wire ce_fref_700khz,
    output wire ce_fref_800khz,
    output wire ce_fref_900khz,
    output wire ce_fref_1000khz
);


    // =========================================================================
    // Stage 1: PLL with 4 outputs (clk_wiz_0 - generated by Vivado)
    // PLL Input: 100MHz
    // PLL Outputs:
    //   - clk_out1 (400MHz) → K/DCO clocks
    //   - clk_out2 (25MHz) → fref_25mhz
    //   - clk_out3 (12.5MHz) → fref_12_5mhz
    //   - clk_out4 (6.25MHz) → fref_6_25mhz
    // =========================================================================
    wire pll_clk_out1, pll_clk_out2, pll_clk_out3, pll_clk_out4;
    
    clk_wiz_0 pll_inst (
        .clk_in1(clk_100mhz),
        .clk_out1(pll_clk_out1),  // 400MHz
        .clk_out2(pll_clk_out2),  // 25MHz
        .clk_out3(pll_clk_out3),  // 12.5MHz
        .clk_out4(pll_clk_out4),  // 6.25MHz
        .locked(k_dco_400mhz_locked),
        .reset(reset)
    );
    
    // PLL output assignments
    assign k_dco_400mhz = pll_clk_out1;
    assign fref_25mhz = pll_clk_out2;
    assign fref_12_5mhz = pll_clk_out3;
    assign fref_6_25mhz = pll_clk_out4;
    assign fref_50mhz = 1'b0;  // Not used (PLL provides 25/12.5/6.25 directly)
    
    // =========================================================================
    // Stage 2: Counter Enable for 10 RO References (100K-1000K)
    // =========================================================================
    // Divisor calculation: 100MHz / (target_freq × 2) = divisor
    // For 100KHz: 100M / (100K × 2) = 500 → count 0-499
    // For 800KHz: 100M / (800K × 2) ≈ 62 → count 0-61
    
    // Counter registers
    reg [9:0] cnt_100khz, cnt_200khz, cnt_300khz, cnt_400khz, cnt_500khz;
    reg [9:0] cnt_600khz, cnt_700khz, cnt_800khz, cnt_900khz, cnt_1000khz;
    
    // Divisor values (count from 0 to divisor-1)
    localparam DIV_100KHZ   = 499;  // 100MHz / (100K*2)
    localparam DIV_200KHZ   = 249;  // 100MHz / (200K*2)
    localparam DIV_300KHZ   = 166;  // 100MHz / (300K*2)
    localparam DIV_400KHZ   = 124;  // 100MHz / (400K*2)
    localparam DIV_500KHZ   = 99;   // 100MHz / (500K*2)
    localparam DIV_600KHZ   = 82;   // 100MHz / (600K*2)
    localparam DIV_700KHZ   = 71;   // 100MHz / (700K*2)
    localparam DIV_800KHZ   = 61;   // 100MHz / (800K*2)
    localparam DIV_900KHZ   = 55;   // 100MHz / (900K*2)
    localparam DIV_1000KHZ  = 49;   // 100MHz / (1000K*2)
    
    // Counter logic with Clock Enable outputs
    always @(posedge clk_100mhz or posedge reset) begin
        if (reset) begin
            cnt_100khz <= 0;
            cnt_200khz <= 0;
            cnt_300khz <= 0;
            cnt_400khz <= 0;
            cnt_500khz <= 0;
            cnt_600khz <= 0;
            cnt_700khz <= 0;
            cnt_800khz <= 0;
            cnt_900khz <= 0;
            cnt_1000khz <= 0;
        end else begin
            // 100 KHz counter
            if (cnt_100khz >= DIV_100KHZ)
                cnt_100khz <= 0;
            else
                cnt_100khz <= cnt_100khz + 1;
            
            // 200 KHz counter
            if (cnt_200khz >= DIV_200KHZ)
                cnt_200khz <= 0;
            else
                cnt_200khz <= cnt_200khz + 1;
            
            // 300 KHz counter
            if (cnt_300khz >= DIV_300KHZ)
                cnt_300khz <= 0;
            else
                cnt_300khz <= cnt_300khz + 1;
            
            // 400 KHz counter
            if (cnt_400khz >= DIV_400KHZ)
                cnt_400khz <= 0;
            else
                cnt_400khz <= cnt_400khz + 1;
            
            // 500 KHz counter
            if (cnt_500khz >= DIV_500KHZ)
                cnt_500khz <= 0;
            else
                cnt_500khz <= cnt_500khz + 1;
            
            // 600 KHz counter
            if (cnt_600khz >= DIV_600KHZ)
                cnt_600khz <= 0;
            else
                cnt_600khz <= cnt_600khz + 1;
            
            // 700 KHz counter
            if (cnt_700khz >= DIV_700KHZ)
                cnt_700khz <= 0;
            else
                cnt_700khz <= cnt_700khz + 1;
            
            // 800 KHz counter
            if (cnt_800khz >= DIV_800KHZ)
                cnt_800khz <= 0;
            else
                cnt_800khz <= cnt_800khz + 1;
            
            // 900 KHz counter
            if (cnt_900khz >= DIV_900KHZ)
                cnt_900khz <= 0;
            else
                cnt_900khz <= cnt_900khz + 1;
            
            // 1000 KHz counter
            if (cnt_1000khz >= DIV_1000KHZ)
                cnt_1000khz <= 0;
            else
                cnt_1000khz <= cnt_1000khz + 1;
        end
    end
    
    // Clock Enable outputs (pulse when counter reaches max)
    assign ce_fref_100khz  = (cnt_100khz >= DIV_100KHZ);
    assign ce_fref_200khz  = (cnt_200khz >= DIV_200KHZ);
    assign ce_fref_300khz  = (cnt_300khz >= DIV_300KHZ);
    assign ce_fref_400khz  = (cnt_400khz >= DIV_400KHZ);
    assign ce_fref_500khz  = (cnt_500khz >= DIV_500KHZ);
    assign ce_fref_600khz  = (cnt_600khz >= DIV_600KHZ);
    assign ce_fref_700khz  = (cnt_700khz >= DIV_700KHZ);
    assign ce_fref_800khz  = (cnt_800khz >= DIV_800KHZ);
    assign ce_fref_900khz  = (cnt_900khz >= DIV_900KHZ);
    assign ce_fref_1000khz = (cnt_1000khz >= DIV_1000KHZ);

endmodule
    
    always @(posedge clk_100mhz or posedge reset) begin
        if (reset) begin
            // Reset all counters and outputs
            counter_fref_100khz <= 0; counter_k_100khz <= 0; counter_dco_100khz <= 0;
            counter_fref_200khz <= 0; counter_k_200khz <= 0; counter_dco_200khz <= 0;
            counter_fref_300khz <= 0; counter_k_300khz <= 0; counter_dco_300khz <= 0;
            counter_fref_400khz <= 0; counter_k_400khz <= 0; counter_dco_400khz <= 0;
            counter_fref_500khz <= 0; counter_k_500khz <= 0; counter_dco_500khz <= 0;
            counter_fref_600khz <= 0; counter_k_600khz <= 0; counter_dco_600khz <= 0;
            counter_fref_700khz <= 0; counter_k_700khz <= 0; counter_dco_700khz <= 0;
            counter_fref_800khz <= 0; counter_k_800khz <= 0; counter_dco_800khz <= 0;
            counter_fref_900khz <= 0; counter_k_900khz <= 0; counter_dco_900khz <= 0;
            counter_fref_1000khz <= 0; counter_k_1000khz <= 0; counter_dco_1000khz <= 0;
            counter_fref_25mhz <= 0; counter_k_25mhz <= 0; counter_dco_25mhz <= 0;
            counter_fref_12_5mhz <= 0; counter_fref_6_25mhz <= 0;
            
            fref_100khz <= 0; k_clk_100khz <= 0; dco_clk_100khz <= 0;
            fref_200khz <= 0; k_clk_200khz <= 0; dco_clk_200khz <= 0;
            fref_300khz <= 0; k_clk_300khz <= 0; dco_clk_300khz <= 0;
            fref_400khz <= 0; k_clk_400khz <= 0; dco_clk_400khz <= 0;
            fref_500khz <= 0; k_clk_500khz <= 0; dco_clk_500khz <= 0;
            fref_600khz <= 0; k_clk_600khz <= 0; dco_clk_600khz <= 0;
            fref_700khz <= 0; k_clk_700khz <= 0; dco_clk_700khz <= 0;
            fref_800khz <= 0; k_clk_800khz <= 0; dco_clk_800khz <= 0;
            fref_900khz <= 0; k_clk_900khz <= 0; dco_clk_900khz <= 0;
            fref_1000khz <= 0; k_clk_1000khz <= 0; dco_clk_1000khz <= 0;
            fref_25mhz <= 0; k_clk_25mhz <= 0; dco_clk_25mhz <= 0;
            fref_12_5mhz <= 0; fref_6_25mhz <= 0;
        end else begin
            // ===== 100 KHz (M=8, 2N=8) =====
            if (counter_fref_100khz >= 499) begin
                counter_fref_100khz <= 0;
                fref_100khz <= ~fref_100khz;
            end else
                counter_fref_100khz <= counter_fref_100khz + 1;
                
            if (counter_k_100khz >= 61) begin  // 800KHz: 100MHz/(800k*2)=62.5→62
                counter_k_100khz <= 0;
                k_clk_100khz <= ~k_clk_100khz;
            end else
                counter_k_100khz <= counter_k_100khz + 1;
                
            if (counter_dco_100khz >= 61) begin  // 800KHz
                counter_dco_100khz <= 0;
                dco_clk_100khz <= ~dco_clk_100khz;
            end else
                counter_dco_100khz <= counter_dco_100khz + 1;
            
            // ===== 200 KHz (M=8, 2N=8) =====
            if (counter_fref_200khz >= 249) begin
                counter_fref_200khz <= 0;
                fref_200khz <= ~fref_200khz;
            end else
                counter_fref_200khz <= counter_fref_200khz + 1;
                
            if (counter_k_200khz >= 30) begin  // 1600KHz: 100MHz/(1600k*2)=31.25→31
                counter_k_200khz <= 0;
                k_clk_200khz <= ~k_clk_200khz;
            end else
                counter_k_200khz <= counter_k_200khz + 1;
                
            if (counter_dco_200khz >= 30) begin
                counter_dco_200khz <= 0;
                dco_clk_200khz <= ~dco_clk_200khz;
            end else
                counter_dco_200khz <= counter_dco_200khz + 1;
            
            // ===== 300 KHz (M=8, 2N=8) =====
            if (counter_fref_300khz >= 166) begin
                counter_fref_300khz <= 0;
                fref_300khz <= ~fref_300khz;
            end else
                counter_fref_300khz <= counter_fref_300khz + 1;
                
            if (counter_k_300khz >= 20) begin  // 2400KHz: 100MHz/(2400k*2)=20.83→20
                counter_k_300khz <= 0;
                k_clk_300khz <= ~k_clk_300khz;
            end else
                counter_k_300khz <= counter_k_300khz + 1;
                
            if (counter_dco_300khz >= 20) begin
                counter_dco_300khz <= 0;
                dco_clk_300khz <= ~dco_clk_300khz;
            end else
                counter_dco_300khz <= counter_dco_300khz + 1;
            
            // ===== 400 KHz (M=8, 2N=8) =====
            if (counter_fref_400khz >= 124) begin
                counter_fref_400khz <= 0;
                fref_400khz <= ~fref_400khz;
            end else
                counter_fref_400khz <= counter_fref_400khz + 1;
                
            if (counter_k_400khz >= 15) begin  // 3200KHz
                counter_k_400khz <= 0;
                k_clk_400khz <= ~k_clk_400khz;
            end else
                counter_k_400khz <= counter_k_400khz + 1;
                
            if (counter_dco_400khz >= 15) begin
                counter_dco_400khz <= 0;
                dco_clk_400khz <= ~dco_clk_400khz;
            end else
                counter_dco_400khz <= counter_dco_400khz + 1;
            
            // ===== 500 KHz (M=8, 2N=8) =====
            if (counter_fref_500khz >= 99) begin
                counter_fref_500khz <= 0;
                fref_500khz <= ~fref_500khz;
            end else
                counter_fref_500khz <= counter_fref_500khz + 1;
                
            if (counter_k_500khz >= 12) begin  // 4000KHz
                counter_k_500khz <= 0;
                k_clk_500khz <= ~k_clk_500khz;
            end else
                counter_k_500khz <= counter_k_500khz + 1;
                
            if (counter_dco_500khz >= 12) begin
                counter_dco_500khz <= 0;
                dco_clk_500khz <= ~dco_clk_500khz;
            end else
                counter_dco_500khz <= counter_dco_500khz + 1;
            
            // ===== 600 KHz (M=8, 2N=8) =====
            if (counter_fref_600khz >= 82) begin
                counter_fref_600khz <= 0;
                fref_600khz <= ~fref_600khz;
            end else
                counter_fref_600khz <= counter_fref_600khz + 1;
                
            if (counter_k_600khz >= 10) begin  // 4800KHz
                counter_k_600khz <= 0;
                k_clk_600khz <= ~k_clk_600khz;
            end else
                counter_k_600khz <= counter_k_600khz + 1;
                
            if (counter_dco_600khz >= 10) begin
                counter_dco_600khz <= 0;
                dco_clk_600khz <= ~dco_clk_600khz;
            end else
                counter_dco_600khz <= counter_dco_600khz + 1;
            
            // ===== 700 KHz (M=8, 2N=8) =====
            if (counter_fref_700khz >= 71) begin
                counter_fref_700khz <= 0;
                fref_700khz <= ~fref_700khz;
            end else
                counter_fref_700khz <= counter_fref_700khz + 1;
                
            if (counter_k_700khz >= 8) begin  // 5600KHz
                counter_k_700khz <= 0;
                k_clk_700khz <= ~k_clk_700khz;
            end else
                counter_k_700khz <= counter_k_700khz + 1;
                
            if (counter_dco_700khz >= 8) begin
                counter_dco_700khz <= 0;
                dco_clk_700khz <= ~dco_clk_700khz;
            end else
                counter_dco_700khz <= counter_dco_700khz + 1;
            
            // ===== 800 KHz (M=8, 2N=8) =====
            if (counter_fref_800khz >= 62) begin
                counter_fref_800khz <= 0;
                fref_800khz <= ~fref_800khz;
            end else
                counter_fref_800khz <= counter_fref_800khz + 1;
                
            if (counter_k_800khz >= 7) begin  // 6400KHz
                counter_k_800khz <= 0;
                k_clk_800khz <= ~k_clk_800khz;
            end else
                counter_k_800khz <= counter_k_800khz + 1;
                
            if (counter_dco_800khz >= 7) begin
                counter_dco_800khz <= 0;
                dco_clk_800khz <= ~dco_clk_800khz;
            end else
                counter_dco_800khz <= counter_dco_800khz + 1;
            
            // ===== 900 KHz (M=8, 2N=8) =====
            if (counter_fref_900khz >= 55) begin
                counter_fref_900khz <= 0;
                fref_900khz <= ~fref_900khz;
            end else
                counter_fref_900khz <= counter_fref_900khz + 1;
                
            if (counter_k_900khz >= 6) begin  // 7200KHz
                counter_k_900khz <= 0;
                k_clk_900khz <= ~k_clk_900khz;
            end else
                counter_k_900khz <= counter_k_900khz + 1;
                
            if (counter_dco_900khz >= 6) begin
                counter_dco_900khz <= 0;
                dco_clk_900khz <= ~dco_clk_900khz;
            end else
                counter_dco_900khz <= counter_dco_900khz + 1;
            
            // ===== 1000 KHz (M=8, 2N=8) =====
            if (counter_fref_1000khz >= 49) begin
                counter_fref_1000khz <= 0;
                fref_1000khz <= ~fref_1000khz;
            end else
                counter_fref_1000khz <= counter_fref_1000khz + 1;
                
            if (counter_k_1000khz >= 6) begin  // 8000KHz
                counter_k_1000khz <= 0;
                k_clk_1000khz <= ~k_clk_1000khz;
            end else
                counter_k_1000khz <= counter_k_1000khz + 1;
                
            if (counter_dco_1000khz >= 6) begin
                counter_dco_1000khz <= 0;
                dco_clk_1000khz <= ~dco_clk_1000khz;
            end else
                counter_dco_1000khz <= counter_dco_1000khz + 1;
            
            // ===== Conventional ADPLL @ 25MHz (K=4, M=16, N=8) =====
            if (counter_fref_25mhz >= 1) begin  // 25MHz
                counter_fref_25mhz <= 0;
                fref_25mhz <= ~fref_25mhz;
            end else
                counter_fref_25mhz <= counter_fref_25mhz + 1;
                
            if (counter_k_25mhz >= 0) begin  // 400MHz (M=16: 16*25M=400M)
                counter_k_25mhz <= 0;
                k_clk_25mhz <= ~k_clk_25mhz;
            end else
                counter_k_25mhz <= counter_k_25mhz + 1;
                
            if (counter_dco_25mhz >= 0) begin  // 400MHz (2N=16: 16*25M=400M)
                counter_dco_25mhz <= 0;
                dco_clk_25mhz <= ~dco_clk_25mhz;
            end else
                counter_dco_25mhz <= counter_dco_25mhz + 1;
            
            // ===== Conventional ADPLL @ 12.5MHz =====
            if (counter_fref_12_5mhz >= 3) begin
                counter_fref_12_5mhz <= 0;
                fref_12_5mhz <= ~fref_12_5mhz;
            end else
                counter_fref_12_5mhz <= counter_fref_12_5mhz + 1;
            
            // ===== Conventional ADPLL @ 6.25MHz =====
            if (counter_fref_6_25mhz >= 7) begin
                counter_fref_6_25mhz <= 0;
                fref_6_25mhz <= ~fref_6_25mhz;
            end else
                counter_fref_6_25mhz <= counter_fref_6_25mhz + 1;
        end
    end

endmodule
